// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/person.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePersonRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Club                 string   `protobuf:"bytes,2,opt,name=club,proto3" json:"club,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePersonRequest) Reset()         { *m = CreatePersonRequest{} }
func (m *CreatePersonRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePersonRequest) ProtoMessage()    {}
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{0}
}

func (m *CreatePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePersonRequest.Unmarshal(m, b)
}
func (m *CreatePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePersonRequest.Marshal(b, m, deterministic)
}
func (m *CreatePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePersonRequest.Merge(m, src)
}
func (m *CreatePersonRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePersonRequest.Size(m)
}
func (m *CreatePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePersonRequest proto.InternalMessageInfo

func (m *CreatePersonRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePersonRequest) GetClub() string {
	if m != nil {
		return m.Club
	}
	return ""
}

type CreatePersonResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Name                 string   `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Club                 string   `protobuf:"bytes,12,opt,name=club,proto3" json:"club,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePersonResponse) Reset()         { *m = CreatePersonResponse{} }
func (m *CreatePersonResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePersonResponse) ProtoMessage()    {}
func (*CreatePersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a772b4d5200054a8, []int{1}
}

func (m *CreatePersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePersonResponse.Unmarshal(m, b)
}
func (m *CreatePersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePersonResponse.Marshal(b, m, deterministic)
}
func (m *CreatePersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePersonResponse.Merge(m, src)
}
func (m *CreatePersonResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePersonResponse.Size(m)
}
func (m *CreatePersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePersonResponse proto.InternalMessageInfo

func (m *CreatePersonResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreatePersonResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreatePersonResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePersonResponse) GetClub() string {
	if m != nil {
		return m.Club
	}
	return ""
}

func init() {
	proto.RegisterType((*CreatePersonRequest)(nil), "person.CreatePersonRequest")
	proto.RegisterType((*CreatePersonResponse)(nil), "person.CreatePersonResponse")
}

func init() { proto.RegisterFile("pb/person.proto", fileDescriptor_a772b4d5200054a8) }

var fileDescriptor_a772b4d5200054a8 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0xd2, 0x2f,
	0x48, 0x2d, 0x2a, 0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94,
	0x6c, 0xb9, 0x84, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x03, 0xc0, 0xfc, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x30, 0x1b, 0x24, 0x96, 0x9c, 0x53, 0x9a, 0x24, 0xc1, 0x04, 0x11, 0x03, 0xb1, 0x95,
	0x72, 0xb8, 0x44, 0x50, 0xb5, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x15,
	0x97, 0x24, 0x96, 0x94, 0x16, 0x83, 0x4d, 0x60, 0x0e, 0x82, 0xf2, 0x84, 0x44, 0xb8, 0x58, 0x53,
	0x8b, 0x8a, 0xf2, 0x8b, 0xa0, 0x86, 0x40, 0x38, 0x70, 0xdb, 0xb8, 0xb1, 0xd8, 0xc6, 0x83, 0xb0,
	0xcd, 0x28, 0x86, 0x8b, 0x17, 0x62, 0x4f, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x37,
	0x17, 0x0f, 0xb2, 0xf5, 0x42, 0xd2, 0x7a, 0x50, 0x4f, 0x62, 0xf1, 0x93, 0x94, 0x0c, 0x76, 0x49,
	0x88, 0x8b, 0x95, 0x18, 0x9c, 0x04, 0xa3, 0xf8, 0xf5, 0xa0, 0x81, 0xa4, 0x5b, 0x5c, 0x96, 0xac,
	0x5f, 0x90, 0x94, 0xc4, 0x06, 0x0e, 0x2c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x00,
	0x8c, 0x46, 0x3f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonServiceClient is the client API for PersonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonServiceClient interface {
	CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error) {
	out := new(CreatePersonResponse)
	err := c.cc.Invoke(ctx, "/person.PersonService/CreatePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServiceServer is the server API for PersonService service.
type PersonServiceServer interface {
	CreatePerson(context.Context, *CreatePersonRequest) (*CreatePersonResponse, error)
}

// UnimplementedPersonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPersonServiceServer struct {
}

func (*UnimplementedPersonServiceServer) CreatePerson(ctx context.Context, req *CreatePersonRequest) (*CreatePersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePerson not implemented")
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).CreatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/person.PersonService/CreatePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).CreatePerson(ctx, req.(*CreatePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "person.PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePerson",
			Handler:    _PersonService_CreatePerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/person.proto",
}
